server:
  address: 0.0.0.0
  port: 8090
camel:
  springboot:
    name: ServicesRest
  component:
    servlet:
      mapping:
        contextPath: '/*'
management:
  address: 0.0.0.0
  port: 8081
endpoints:
  enabled: false
  health:
    enabled: true
quickstart:
  generateOrderPeriod: 10s
  processOrderPeriod: 30s
logging:
  config: 'classpath:logback.xml'