server:
  address: 0.0.0.0
  port: 8090
camel:
  springboot:
    name: ServicesRest
#    camel.component.servlet.mapping.context-path
     #
     #Context path used by the servlet component for automatic mapping.
     #
     #/camel/*
  component:
    servlet:
      mapping:
        contextPath: '/*'
management:
  address: 0.0.0.0
  port: 8081
endpoints:
  enabled: false
  health:
    enabled: true
quickstart:
  generateOrderPeriod: 10s
  processOrderPeriod: 30s
logging:
  config: 'classpath:logback.xml'